"use client";

import { useEffect, useMemo, useRef, useState, type ClipboardEvent, type KeyboardEvent } from "react";
import { dateControlClassName, formatPortalEditableDate, isoToPortalDateParts, normalizePortalDateInput, portalDateToIso } from "@/components/portal-date-utils";

type Parts = ReturnType<typeof isoToPortalDateParts>;
type Props = { id: string; value: string | null; onChange: (value: string | null) => void; onValidityChange?: (valid: boolean) => void; disabled?: boolean; nullable?: boolean; ariaDescribedBy?: string; invalidLabel: string; incompleteLabel: string; todayLabel: string; clearLabel: string; openCalendarLabel: string; previousMonthLabel: string; nextMonthLabel: string; };

export { formatPortalEditableDate as formatEditableDate, portalDateToIso as parseEditableDate } from "@/components/portal-date-utils";

export function PortalDateInput({ id, value, onChange, onValidityChange, disabled = false, nullable = true, ariaDescribedBy, invalidLabel, incompleteLabel, todayLabel, clearLabel, openCalendarLabel, previousMonthLabel, nextMonthLabel }: Props) {
  const [parts, setParts] = useState<Parts>(() => isoToPortalDateParts(value));
  const [touched, setTouched] = useState(false); const [isOpen, setIsOpen] = useState(false); const [month, setMonth] = useState(() => monthFor(value));
  const root = useRef<HTMLDivElement>(null); const refs = [useRef<HTMLInputElement>(null), useRef<HTMLInputElement>(null), useRef<HTMLInputElement>(null)];
  const iso = portalDateToIso(parts.day, parts.month, parts.year); const empty = !parts.day && !parts.month && !parts.year; const invalid = touched && !empty && !iso;
  useEffect(() => { const next = isoToPortalDateParts(value); setParts(next); setTouched(false); setMonth(monthFor(value)); }, [value]);
  useEffect(() => onValidityChange?.(empty || Boolean(iso)), [empty, iso, onValidityChange]);
  useEffect(() => { function outside(event: MouseEvent) { if (root.current && !root.current.contains(event.target as Node)) setIsOpen(false); } document.addEventListener("mousedown", outside); return () => document.removeEventListener("mousedown", outside); }, []);
  function update(next: Parts, focus?: number) { setParts(next); const parsed = portalDateToIso(next.day, next.month, next.year); if (parsed) onChange(parsed); else if (!next.day && !next.month && !next.year) onChange(null); if (focus !== undefined) queueMicrotask(() => refs[focus].current?.focus()); }
  function paste(event: ClipboardEvent<HTMLInputElement>) { event.preventDefault(); const next = normalizePortalDateInput(event.clipboardData.getData("text")); update(next, next.year.length === 4 ? undefined : next.month.length === 2 ? 2 : next.day.length === 2 ? 1 : 0); setTouched(true); }
  function keyDown(event: KeyboardEvent<HTMLInputElement>, index: number) { if (event.key === "ArrowLeft" && index > 0) { event.preventDefault(); refs[index - 1].current?.focus(); } else if (event.key === "ArrowRight" && index < 2) { event.preventDefault(); refs[index + 1].current?.focus(); } else if (event.key === "Backspace" && ![parts.day, parts.month, parts.year][index] && index > 0) { event.preventDefault(); refs[index - 1].current?.focus(); } else if (event.key === "Delete") { event.preventDefault(); const next = { ...parts }; (next as Record<string, string>)[["day", "month", "year"][index]] = ""; update(next); setTouched(true); } else if (event.key === "Escape") { setIsOpen(false); refs[index].current?.focus(); } }
  function choose(isoDate: string) { onChange(isoDate); setParts(isoToPortalDateParts(isoDate)); setTouched(false); setMonth(monthFor(isoDate)); setIsOpen(false); refs[0].current?.focus(); }
  const days = useMemo(() => calendarDays(month), [month]);
  return <div ref={root} className="relative" onBlurCapture={() => window.setTimeout(() => { if (!root.current?.contains(document.activeElement)) setTouched(true); }, 0)}><div className="flex items-stretch gap-2"><div className={`inline-flex min-h-10 w-[9rem] shrink-0 items-center leading-5 ${dateControlClassName({ invalid, focusWithin: true })} ${disabled ? "cursor-not-allowed" : ""}`}>
    {(["day", "month", "year"] as const).map((name, index) => <span key={name} className="contents"><input ref={refs[index]} id={index === 0 ? id : undefined} aria-label={`${id} ${name}`} aria-describedby={ariaDescribedBy} aria-invalid={invalid || undefined} disabled={disabled} inputMode="numeric" maxLength={index === 2 ? 4 : 2} value={parts[name]} placeholder={index === 0 ? "dd" : index === 1 ? "mm" : "yyyy"} onFocus={(event) => event.currentTarget.select()} onPaste={paste} onKeyDown={(event) => keyDown(event, index)} onChange={(event) => { const digits = event.target.value.replace(/\D/g, "").slice(0, index === 2 ? 4 : 2); const next = { ...parts, [name]: digits }; update(next, digits.length === (index === 2 ? 4 : 2) && index < 2 ? index + 1 : undefined); }} className={`min-w-0 shrink-0 bg-transparent p-0 text-center text-sm leading-5 text-slate-950 tabular-nums outline-none placeholder:text-slate-400 disabled:cursor-not-allowed ${index === 2 ? "w-[4ch]" : "w-[2ch]"}`} />{index < 2 && <span aria-hidden="true" className="-mx-px text-slate-500">.</span>}</span>)}<span aria-hidden="true" className="-ml-px text-slate-500">.</span></div>
    <button type="button" disabled={disabled} aria-label={openCalendarLabel} aria-expanded={isOpen} onClick={() => setIsOpen((open) => !open)} className={`inline-flex min-h-10 items-center justify-center text-slate-700 ${dateControlClassName({ invalid })}`}>▦</button></div>
    {invalid && <p role="alert" className="mt-1 text-xs text-red-700">{parts.day.length + parts.month.length + parts.year.length < 8 ? incompleteLabel : invalidLabel}</p>}
    {isOpen && <div role="dialog" aria-label={openCalendarLabel} className="absolute z-30 mt-1 w-72 rounded-md border border-slate-300 bg-white p-3 shadow-lg" onKeyDown={(event) => { if (event.key === "Escape") { setIsOpen(false); refs[0].current?.focus(); } }}><div className="mb-2 flex items-center justify-between text-sm font-medium"><button type="button" aria-label={previousMonthLabel} onClick={() => setMonth(addMonths(month, -1))} className="rounded-sm px-1 focus:outline-none focus:ring-2 focus:ring-blue-600">‹</button><span>{new Intl.DateTimeFormat("sr-Latn-RS", { month: "long", year: "numeric" }).format(month)}</span><button type="button" aria-label={nextMonthLabel} onClick={() => setMonth(addMonths(month, 1))} className="rounded-sm px-1 focus:outline-none focus:ring-2 focus:ring-blue-600">›</button></div><div className="grid grid-cols-7 gap-1 text-center text-xs text-slate-500"><span>Po</span><span>Ut</span><span>Sr</span><span>Če</span><span>Pe</span><span>Su</span><span>Ne</span></div><div className="mt-1 grid grid-cols-7 gap-1">{days.map((day, index) => day ? <button key={day.iso} type="button" aria-pressed={day.iso === value} onClick={() => choose(day.iso)} className={`min-h-8 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-600 ${day.iso === value ? "bg-blue-700 text-white" : "hover:bg-blue-50"}`}>{day.day}</button> : <span key={`empty-${index}`} />)}</div><div className="mt-3 flex justify-between border-t pt-2"><button type="button" onClick={() => choose(todayIso())} className="rounded-sm text-sm text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600">{todayLabel}</button>{nullable && <button type="button" onClick={() => { update({ day: "", month: "", year: "" }); setTouched(false); setIsOpen(false); refs[0].current?.focus(); }} className="rounded-sm text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-600">{clearLabel}</button>}</div></div>}</div>;
}
function monthFor(isoDate: string | null | undefined) { const parts = isoToPortalDateParts(isoDate); return parts.year ? new Date(Number(parts.year), Number(parts.month) - 1, 1) : new Date(new Date().getFullYear(), new Date().getMonth(), 1); }
function addMonths(value: Date, offset: number) { return new Date(value.getFullYear(), value.getMonth() + offset, 1); }
function todayIso() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`; }
function calendarDays(month: Date) { const leading = (month.getDay() + 6) % 7; const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(leading).fill(null), ...Array.from({ length: count }, (_, index) => { const day = index + 1; return { day, iso: `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}` }; })]; }
