using Dapper;
using InternalApps.Api.Infrastructure;
using InternalApps.Api.Modules.Vacation;
using Npgsql;
using Xunit;

namespace InternalApps.Api.Tests;

public sealed class VacationAdr0007Increment1Tests
{
    [Fact]
    public void Migrations_ImplementOnlyTheApprovedIncrementOneFoundation()
    {
        var identity = Read("database", "migrations", "036_vacation_leave_request_identities.sql");
        var ledger = Read("database", "migrations", "037_vacation_ledger_request_existence_hardening.sql");
        var markers = Read("database", "migrations", "038_vacation_leave_type_protected_dependencies.sql");
        var system = Read("database", "migrations", "039_vacation_system_leave_types.sql");

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", identity);
        Assert.Contains("FOREIGN KEY (id, public_id)", identity);
        Assert.Contains("REFERENCES vacation.leave_request_identities (id)", identity);
        Assert.Contains("ON DELETE NO ACTION", identity);
        Assert.DoesNotContain("UPDATE vacation.leave_balance_entries", identity);
        Assert.DoesNotContain("DELETE FROM vacation.leave_balance_entries", identity);
        Assert.Contains("IF NOT FOUND THEN", ledger);
        Assert.Contains("existing operational leave request", ledger);
        Assert.True(ledger.Split("IS DISTINCT FROM").Length >= 10);
        Assert.Contains("vacation.leave_type_protected_dependencies", markers);
        Assert.Contains("ON CONFLICT (leave_type_id, dependency_name) DO NOTHING", markers);
        Assert.Contains("System leave type", system);
        Assert.DoesNotContain("GRANT DELETE", identity + ledger + markers + system);
        Assert.DoesNotContain("ON DELETE CASCADE", identity + ledger + markers + system,
            StringComparison.OrdinalIgnoreCase);
        Assert.False(File.Exists(Path.Combine(RepositoryRoot(), "database", "migrations",
            "040_vacation_delete_permissions.sql")));
        Assert.False(File.Exists(Path.Combine(RepositoryRoot(), "database", "migrations",
            "041_vacation_delete_neutralized_leave_request.sql")));
    }

    [Fact]
    public void RequestCreation_IsIdentityFirstAndTransactionalAtTheExistingServiceBoundary()
    {
        var repository = Read("apps", "api", "src", "Api", "Modules", "Vacation",
            "LeaveRequestsRepository.cs");
        var service = Read("apps", "api", "src", "Api", "Modules", "Vacation",
            "LeaveRequestService.cs");
        var create = repository[repository.IndexOf("WITH new_identity AS", StringComparison.Ordinal)..];

        Assert.Contains("INSERT INTO vacation.leave_request_identities", create);
        Assert.Contains("DEFAULT VALUES", create);
        Assert.Contains("new_identity.id, new_identity.public_id", create);
        Assert.True(create.IndexOf("leave_request_identities", StringComparison.Ordinal) <
                    create.IndexOf("INSERT INTO vacation.leave_requests", StringComparison.Ordinal));
        Assert.Contains("BeginTransactionAsync", service);
        Assert.Contains("CommitAsync", service);
    }

    [Fact]
    public async Task PermanentIdentitySchema_BackfillSequenceRelationshipsAndImmutability_AreEnforced()
    {
        if (!DatabaseIntegrationEnabled()) return;
        await using var dataSource = NpgsqlDataSource.Create(BuildOwnerConnectionString());
        await using var connection = await dataSource.OpenConnectionAsync();

        var unmatched = await connection.ExecuteScalarAsync<int>("""
            SELECT count(*)
            FROM vacation.leave_requests AS requests
            FULL JOIN vacation.leave_request_identities AS identities
              ON identities.id = requests.id AND identities.public_id = requests.public_id
            WHERE requests.id IS NULL OR identities.id IS NULL
            """);
        Assert.Equal(0, unmatched);

        var sequenceIsAbove = await connection.ExecuteScalarAsync<bool>("""
            SELECT last_value >= coalesce((SELECT max(id) FROM vacation.leave_request_identities), 0)
            FROM vacation.leave_request_identities_id_seq
            """);
        Assert.True(sequenceIsAbove);

        var relationships = (await connection.QueryAsync<(string Name, string Target, string DeleteAction)>("""
            SELECT constraints.conname AS Name,
                   constraints.confrelid::regclass::text AS Target,
                   constraints.confdeltype::text AS DeleteAction
            FROM pg_constraint AS constraints
            WHERE constraints.conname IN (
                'fk_vacation_leave_requests_identity',
                'fk_vacation_leave_balance_entries_request_identity')
            ORDER BY constraints.conname
            """)).ToArray();
        Assert.Equal(2, relationships.Length);
        Assert.All(relationships, relationship =>
        {
            Assert.Equal("vacation.leave_request_identities", relationship.Target);
            Assert.Equal("a", relationship.DeleteAction);
        });

        await using var transaction = await connection.BeginTransactionAsync();
        var identity = await connection.QuerySingleAsync<(long Id, Guid PublicId)>("""
            INSERT INTO vacation.leave_request_identities DEFAULT VALUES
            RETURNING id AS Id, public_id AS PublicId
            """, transaction: transaction);
        await AssertDatabaseFailureAsync(connection, transaction,
            "UPDATE vacation.leave_request_identities SET public_id = gen_random_uuid() WHERE id = @id",
            new { identity.Id }, "Leave request identities are immutable.");
        await AssertDatabaseFailureAsync(connection, transaction,
            "DELETE FROM vacation.leave_request_identities WHERE id = @id",
            new { identity.Id }, "Leave request identities are immutable.");
        await transaction.RollbackAsync();
    }

    [Fact]
    public async Task LedgerTrigger_RejectsAbsentRequestsAndPreservesValidPostingInvariants()
    {
        if (!DatabaseIntegrationEnabled()) return;
        LoadRepositoryEnvironment();
        SqlMapper.AddTypeHandler(new DateOnlyTypeHandler());
        await using var dataSource = NpgsqlDataSource.Create(BuildOwnerConnectionString());
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var transaction = await connection.BeginTransactionAsync();

        var scope = await connection.QuerySingleAsync<(long EmployeeId, long LeaveTypeId, long UserId)>("""
            SELECT employees.id AS EmployeeId, leave_types.id AS LeaveTypeId, users.id AS UserId
            FROM organization.employees AS employees
            CROSS JOIN vacation.leave_types AS leave_types
            CROSS JOIN identity.users AS users
            WHERE leave_types.requires_balance
            ORDER BY employees.id, leave_types.id, users.id LIMIT 1
            """, transaction: transaction);
        var identityId = await connection.ExecuteScalarAsync<long>("""
            INSERT INTO vacation.leave_request_identities DEFAULT VALUES RETURNING id
            """, transaction: transaction);

        await connection.ExecuteAsync("""
            INSERT INTO vacation.leave_balance_entries
                (employee_id, leave_type_id, leave_year, entry_kind, quantity_days,
                 effective_date, actor_user_id, reason, source_reference)
            VALUES (@EmployeeId, @LeaveTypeId, 2997, 'annual_entitlement', 5,
                    DATE '2997-01-01', @UserId, 'ADR-0007 fixture credit', gen_random_uuid()::text)
            """, new { scope.EmployeeId, scope.LeaveTypeId, scope.UserId }, transaction);

        await AssertDatabaseFailureAsync(connection, transaction, """
            INSERT INTO vacation.leave_balance_entries
                (employee_id, leave_type_id, leave_year, entry_kind, quantity_days,
                 effective_date, actor_user_id, reason, source_reference, leave_request_id)
            VALUES (@EmployeeId, @LeaveTypeId, 2997, 'request_consumption', -1,
                    DATE '2997-02-01', @UserId, 'Absent request', @IdentityId::text, @IdentityId)
            """, new { scope.EmployeeId, scope.LeaveTypeId, scope.UserId, IdentityId = identityId },
            "Leave balance entries require an existing operational leave request.");

        var requestIdentity = await connection.QuerySingleAsync<(long Id, Guid PublicId)>("""
            INSERT INTO vacation.leave_request_identities DEFAULT VALUES
            RETURNING id AS Id, public_id AS PublicId
            """, transaction: transaction);
        await connection.ExecuteAsync("""
            INSERT INTO vacation.leave_requests
                (id, public_id, employee_id, leave_type_id, date_from, date_to,
                 working_days, status, submitted_at, decided_at, decided_by_user_id,
                 created_by_user_id)
            VALUES (@Id, @PublicId, @EmployeeId, @LeaveTypeId, DATE '2997-03-01',
                    DATE '2997-03-01', 1, 'APPROVED', now(), now(), @UserId, @UserId)
            """, new { requestIdentity.Id, requestIdentity.PublicId, scope.EmployeeId,
                scope.LeaveTypeId, scope.UserId }, transaction);
        var consumptionId = await connection.ExecuteScalarAsync<long>("""
            INSERT INTO vacation.leave_balance_entries
                (employee_id, leave_type_id, leave_year, entry_kind, quantity_days,
                 effective_date, actor_user_id, reason, source_reference, leave_request_id)
            VALUES (@EmployeeId, @LeaveTypeId, 2997, 'request_consumption', -1,
                    DATE '2997-03-01', @UserId, 'Valid consumption', @Id::text, @Id)
            RETURNING id
            """, new { scope.EmployeeId, scope.LeaveTypeId, scope.UserId, requestIdentity.Id },
            transaction);
        await connection.ExecuteAsync("""
            UPDATE vacation.leave_requests
            SET status = 'CANCELLED', cancelled_at = now(), cancelled_by_user_id = @UserId
            WHERE id = @Id
            """, new { scope.UserId, requestIdentity.Id }, transaction);
        await connection.ExecuteAsync("""
            INSERT INTO vacation.leave_balance_entries
                (employee_id, leave_type_id, leave_year, entry_kind, quantity_days,
                 effective_date, actor_user_id, reason, source_reference,
                 leave_request_id, reverses_entry_id)
            VALUES (@EmployeeId, @LeaveTypeId, 2997, 'cancellation_reversal', 1,
                    DATE '2997-03-01', @UserId, 'Valid reversal', @Id::text, @Id, @ConsumptionId)
            """, new { scope.EmployeeId, scope.LeaveTypeId, scope.UserId,
                requestIdentity.Id, ConsumptionId = consumptionId }, transaction);

        await transaction.RollbackAsync();
    }

    [Fact]
    public async Task LeaveTypeMarkersAndSystemProtection_ArePermanentLeastPrivilegeFacts()
    {
        if (!DatabaseIntegrationEnabled()) return;
        await using var dataSource = NpgsqlDataSource.Create(BuildOwnerConnectionString());
        await using var connection = await dataSource.OpenConnectionAsync();

        var missingMarkers = await connection.ExecuteScalarAsync<int>("""
            SELECT count(*) FROM (
                SELECT leave_type_id, 'Vacation leave request'::text dependency_name FROM vacation.leave_requests
                UNION SELECT leave_type_id, 'Vacation leave balance' FROM vacation.leave_balances
                UNION SELECT leave_type_id, 'Vacation leave balance entry' FROM vacation.leave_balance_entries
            ) expected
            LEFT JOIN vacation.leave_type_protected_dependencies actual USING (leave_type_id, dependency_name)
            WHERE actual.leave_type_id IS NULL
            """);
        Assert.Equal(0, missingMarkers);

        var systemCodes = (await connection.QueryAsync<string>("""
            SELECT code FROM vacation.leave_types WHERE is_system ORDER BY code
            """)).ToArray();
        Assert.Equal(["ANNUAL_LEAVE", "OTHER", "PAID_LEAVE", "SICK_LEAVE", "UNPAID_LEAVE"], systemCodes);

        Assert.False(await connection.ExecuteScalarAsync<bool>("""
            SELECT has_column_privilege('internal_apps_app', 'vacation.leave_types', 'is_system', 'INSERT')
                OR has_column_privilege('internal_apps_app', 'vacation.leave_types', 'is_system', 'UPDATE')
            """));
        Assert.False(await connection.ExecuteScalarAsync<bool>("""
            SELECT has_table_privilege('internal_apps_app',
                'vacation.leave_type_protected_dependencies', 'SELECT,INSERT,UPDATE,DELETE')
            """));

        await using var transaction = await connection.BeginTransactionAsync();
        var systemPublicId = await connection.ExecuteScalarAsync<Guid>("""
            SELECT public_id FROM vacation.leave_types WHERE code = 'ANNUAL_LEAVE'
            """, transaction: transaction);
        await AssertDatabaseFailureAsync(connection, transaction,
            "SELECT vacation.delete_unreferenced_leave_type(@systemPublicId)",
            new { systemPublicId }, "leave_type_delete_conflict:v1:System leave type");

        var fixture = await connection.QuerySingleAsync<(long LeaveTypeId, Guid LeaveTypePublicId,
            long EmployeeId, long UserId)>("""
            WITH new_type AS (
                INSERT INTO vacation.leave_types
                    (code, name_sr, name_en, counts_against_vacation_balance,
                     requires_balance, requires_approval, is_active, display_order)
                VALUES ('ADR7_' || upper(replace(left(gen_random_uuid()::text, 12), '-', '_')),
                        'ADR test', 'ADR test', false, false, false, true, 999)
                RETURNING id, public_id
            )
            SELECT new_type.id AS LeaveTypeId, new_type.public_id AS LeaveTypePublicId,
                   employees.id AS EmployeeId, users.id AS UserId
            FROM new_type CROSS JOIN organization.employees AS employees
            CROSS JOIN identity.users AS users
            ORDER BY employees.id, users.id LIMIT 1
            """, transaction: transaction);
        var request = await connection.QuerySingleAsync<(long Id, Guid PublicId)>("""
            WITH new_identity AS (
                INSERT INTO vacation.leave_request_identities DEFAULT VALUES
                RETURNING id, public_id
            )
            INSERT INTO vacation.leave_requests
                (id, public_id, employee_id, leave_type_id, date_from, date_to,
                 working_days, status, created_by_user_id)
            SELECT id, public_id, @EmployeeId, @LeaveTypeId, DATE '2996-01-02',
                   DATE '2996-01-02', 1, 'SUBMITTED', @UserId
            FROM new_identity RETURNING id AS Id, public_id AS PublicId
            """, new { fixture.EmployeeId, fixture.LeaveTypeId, fixture.UserId }, transaction);
        await connection.ExecuteAsync("DELETE FROM vacation.leave_requests WHERE id = @Id",
            new { request.Id }, transaction);
        Assert.Equal(1, await connection.ExecuteScalarAsync<int>("""
            SELECT count(*) FROM vacation.leave_type_protected_dependencies
            WHERE leave_type_id = @LeaveTypeId AND dependency_name = 'Vacation leave request'
            """, new { fixture.LeaveTypeId }, transaction));
        Assert.Equal(1, await connection.ExecuteScalarAsync<int>("""
            SELECT count(*) FROM organization.employee_protected_dependencies
            WHERE employee_id = @EmployeeId AND dependency_name = 'Vacation leave request'
            """, new { fixture.EmployeeId }, transaction));
        await AssertDatabaseFailureAsync(connection, transaction,
            "SELECT vacation.delete_unreferenced_leave_type(@LeaveTypePublicId)",
            new { fixture.LeaveTypePublicId },
            "leave_type_delete_conflict:v1:Vacation leave request");
        await transaction.RollbackAsync();
    }

    private static async Task AssertDatabaseFailureAsync(NpgsqlConnection connection,
        NpgsqlTransaction transaction, string sql, object parameters, string expectedMessage)
    {
        var savepoint = $"adr_{Guid.NewGuid():N}";
        await transaction.SaveAsync(savepoint);
        var exception = await Assert.ThrowsAsync<PostgresException>(() =>
            connection.ExecuteAsync(sql, parameters, transaction));
        Assert.Equal(PostgresErrorCodes.RaiseException, exception.SqlState);
        Assert.Equal(expectedMessage, exception.MessageText);
        await transaction.RollbackAsync(savepoint);
    }

    private static bool DatabaseIntegrationEnabled() => string.Equals(
        Environment.GetEnvironmentVariable("RUN_DATABASE_INTEGRATION_TESTS"), "true",
        StringComparison.OrdinalIgnoreCase);

    private static string Read(params string[] parts) =>
        File.ReadAllText(Path.Combine([RepositoryRoot(), .. parts]));

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "internal.ps1")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new InvalidOperationException("Repository root not found.");
    }

    private static void LoadRepositoryEnvironment()
    {
        foreach (var line in File.ReadLines(Path.Combine(RepositoryRoot(), ".env")))
        {
            var separator = line.IndexOf('=');
            if (separator <= 0 || line.TrimStart().StartsWith('#')) continue;
            var name = line[..separator].Trim();
            if (Environment.GetEnvironmentVariable(name) is null)
                Environment.SetEnvironmentVariable(name, line[(separator + 1)..].Trim());
        }
    }

    private static string Required(string name) => Environment.GetEnvironmentVariable(name)
        ?? throw new InvalidOperationException($"{name} is required.");

    private static string BuildOwnerConnectionString()
    {
        LoadRepositoryEnvironment();
        return new NpgsqlConnectionStringBuilder
        {
            Host = Required("DB_HOST"), Port = int.Parse(Required("DB_PORT")),
            Database = Required("DB_NAME"), Username = Required("DB_OWNER_USER"),
            Password = Required("DB_OWNER_PASSWORD"),
            SslMode = Enum.Parse<SslMode>(Required("DB_SSL_MODE"), true)
        }.ConnectionString;
    }
}
