DO $$
BEGIN
    IF to_regclass('vacation.leave_requests') IS NULL
       OR to_regclass('vacation.leave_balance_entries') IS NULL THEN
        RAISE EXCEPTION 'Migration 036 requires Vacation requests and ledger migrations 013 and 020.';
    END IF;
END
$$;

CREATE TABLE vacation.leave_request_identities
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_vacation_leave_request_identities_public_id UNIQUE (public_id),
    CONSTRAINT uq_vacation_leave_request_identities_id_public_id UNIQUE (id, public_id)
);

CREATE OR REPLACE FUNCTION vacation.prevent_leave_request_identity_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
BEGIN
    RAISE EXCEPTION 'Leave request identities are immutable.';
END
$$;

ALTER FUNCTION vacation.prevent_leave_request_identity_mutation()
OWNER TO internal_apps_owner;

CREATE TRIGGER trg_vacation_leave_request_identities_immutable
BEFORE UPDATE OR DELETE ON vacation.leave_request_identities
FOR EACH ROW EXECUTE FUNCTION vacation.prevent_leave_request_identity_mutation();

INSERT INTO vacation.leave_request_identities (id, public_id, created_at)
SELECT id, public_id, created_at
FROM vacation.leave_requests;

SELECT setval(
    pg_get_serial_sequence('vacation.leave_request_identities', 'id'),
    GREATEST((SELECT coalesce(max(id), 0) FROM vacation.leave_request_identities), 1));

ALTER TABLE vacation.leave_requests
    ALTER COLUMN id DROP IDENTITY;

ALTER TABLE vacation.leave_requests
    ADD CONSTRAINT fk_vacation_leave_requests_identity
        FOREIGN KEY (id, public_id)
        REFERENCES vacation.leave_request_identities (id, public_id)
        ON DELETE NO ACTION;

ALTER TABLE vacation.leave_balance_entries
    DROP CONSTRAINT fk_vacation_leave_balance_entries_request,
    ADD CONSTRAINT fk_vacation_leave_balance_entries_request_identity
        FOREIGN KEY (leave_request_id)
        REFERENCES vacation.leave_request_identities (id)
        ON DELETE NO ACTION;

REVOKE ALL ON vacation.leave_request_identities FROM PUBLIC;
GRANT SELECT, INSERT ON vacation.leave_request_identities TO internal_apps_app;
GRANT USAGE ON SEQUENCE vacation.leave_request_identities_id_seq TO internal_apps_app;
GRANT INSERT (id, public_id) ON vacation.leave_requests TO internal_apps_app;
